# the language
lang: nl
# author info
author:
  name: Haroen Viaene
  email: hell@haroen.me
  twitter: '@haroenv'
# title and description
title: dashboard
description: 'A dashboard for a shuttle mission. See also: https://github.com/jwronline/shuttle-command'
# the url this will be published at
url: http://gh.jwronline.be
baseurl: /dashboard/
# the theme colour
color:
# location of some files
css: ['/dashboard/src/css//style.css','https://api.tiles.mapbox.com/mapbox-gl-js/v0.16.0/mapbox-gl.css']
scripts: ['https://api.tiles.mapbox.com/mapbox-gl-js/v0.16.0/mapbox-gl.js','/dashboard/src/js/main.js']
favicon: ['src/img/favicon.png']
#configuration
sass:
  style: compressed
